# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: nomer26
title: nomer26

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Non-Optional Multiplayer

description: Stylish Jekyll Theme
author:
  name: nomer26
  email: rsh4297@gmail.com
  github: nomer26
  facebook: ryun26
  bio: I'm gonna be a multiplayer who can develop, analyze, manage and etc... Everything !! 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
